# Generated by Django 4.0.5 on 2022-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=100),
        ),
    ]
