# Generated by Django 4.0.5 on 2022-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JobType',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
