# Generated by Django 4.0.5 on 2022-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_jobtype_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('programming', 'programming'), ('freelancing', 'freelancing'), ('designing', 'designing'), ('front end', 'front end')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
